project_name: psync
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  filters:
    exclude:
      - '^TECH'
