version: 2
project_name: psync
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: '{{ .Tag }}'
changelog:
  filters:
    exclude:
      - '^TECH'
